# Generated by Django 4.0.3 on 2022-03-08 18:50

from django.db import migrations, models
import drones.models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_alter_drone_weight_limiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.IntegerField(validators=[drones.models.validate_battery_capacity]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=255),
        ),
    ]
