# Generated by Django 3.2.12 on 2022-03-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_battery_capacity_alter_drone_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryHistoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity', models.IntegerField(default=100, verbose_name='Battery capacity')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drone', verbose_name='drone')),
            ],
            options={
                'verbose_name': 'HistoryBatteryLevel',
                'verbose_name_plural': 'HistoryBatteryLevels',
                'db_table': 'tbl_history_battery_level',
            },
        ),
    ]
