# Generated by Django 3.2.12 on 2022-03-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_batteryhistorylevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteryhistorylevel',
            options={'verbose_name': 'BatteryHistoryLevel', 'verbose_name_plural': 'BatteryHistoryLevel'},
        ),
    ]
