# Generated by Django 4.0.3 on 2022-03-08 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import medications.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0002_alter_drone_weight_limiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadMedicationDrone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('delivered_medication', models.DateTimeField(verbose_name='Initial Date')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drone', verbose_name='Drone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=250, validators=[medications.models.validation_name])),
                ('weight', models.FloatField()),
                ('code', models.CharField(max_length=250, validators=[medications.models.validation_code])),
                ('image', models.ImageField(upload_to='')),
                ('load', models.ManyToManyField(through='medications.LoadMedicationDrone', to='drones.drone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loadmedicationdrone',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication', verbose_name='Medication'),
        ),
    ]
