# Generated by Django 4.0.3 on 2022-03-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_drone_battery_capacity_alter_drone_state'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='load',
            field=models.ManyToManyField(blank=True, null=True, through='medications.LoadMedicationDrone', to='drones.drone'),
        ),
    ]
